/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InvestmentPlan = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'dailyReturn' : IDL.Float64,
  'price' : IDL.Float64,
});
export const PlanId = IDL.Nat;
export const TXId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RechargeStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Recharge = IDL.Record({
  'id' : TXId,
  'status' : RechargeStatus,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'paymentRef' : IDL.Text,
  'amount' : IDL.Float64,
});
export const User = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'totalRecharged' : IDL.Float64,
  'totalEarned' : IDL.Float64,
  'referredBy' : IDL.Opt(IDL.Text),
  'totalWithdrawn' : IDL.Float64,
  'lastDailyClaim' : Timestamp,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Float64,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Withdrawal = IDL.Record({
  'id' : TXId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'paymentDetails' : IDL.Text,
  'timestamp' : Timestamp,
  'amount' : IDL.Float64,
});
export const Investment = IDL.Record({
  'startTime' : Timestamp,
  'active' : IDL.Bool,
  'dailyEarnings' : IDL.Float64,
  'planId' : PlanId,
  'userId' : UserId,
  'totalEarned' : IDL.Float64,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdatePlan' : IDL.Func([InvestmentPlan], [PlanId], []),
  'approveRecharge' : IDL.Func([TXId], [], []),
  'approveWithdrawal' : IDL.Func([TXId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyEarnings' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Float64,
          'dailyLimitReached' : IDL.Null,
          'notRegistered' : IDL.Null,
        }),
      ],
      [],
    ),
  'createInvestment' : IDL.Func(
      [PlanId, IDL.Float64],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'insufficientBalance' : IDL.Null,
          'notFound' : IDL.Null,
        }),
      ],
      [],
    ),
  'createWithdrawal' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [
        IDL.Variant({
          'ok' : TXId,
          'insufficientBalance' : IDL.Null,
          'notRegistered' : IDL.Null,
        }),
      ],
      [],
    ),
  'getAllPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
  'getAllRecharges' : IDL.Func([], [IDL.Vec(Recharge)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReferralTree' : IDL.Func(
      [UserId],
      [
        IDL.Record({
          'level1' : IDL.Vec(UserId),
          'level2' : IDL.Vec(UserId),
          'level3' : IDL.Vec(UserId),
        }),
      ],
      ['query'],
    ),
  'getUserInvestments' : IDL.Func([UserId], [IDL.Vec(Investment)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : User, 'notFound' : IDL.Null })],
      ['query'],
    ),
  'initiateRecharge' : IDL.Func([IDL.Float64, IDL.Text], [TXId], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InvestmentPlan = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'dailyReturn' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const PlanId = IDL.Nat;
  const TXId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RechargeStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Recharge = IDL.Record({
    'id' : TXId,
    'status' : RechargeStatus,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'paymentRef' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const User = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'totalRecharged' : IDL.Float64,
    'totalEarned' : IDL.Float64,
    'referredBy' : IDL.Opt(IDL.Text),
    'totalWithdrawn' : IDL.Float64,
    'lastDailyClaim' : Timestamp,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Float64,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Withdrawal = IDL.Record({
    'id' : TXId,
    'status' : WithdrawalStatus,
    'userId' : UserId,
    'paymentDetails' : IDL.Text,
    'timestamp' : Timestamp,
    'amount' : IDL.Float64,
  });
  const Investment = IDL.Record({
    'startTime' : Timestamp,
    'active' : IDL.Bool,
    'dailyEarnings' : IDL.Float64,
    'planId' : PlanId,
    'userId' : UserId,
    'totalEarned' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdatePlan' : IDL.Func([InvestmentPlan], [PlanId], []),
    'approveRecharge' : IDL.Func([TXId], [], []),
    'approveWithdrawal' : IDL.Func([TXId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyEarnings' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Float64,
            'dailyLimitReached' : IDL.Null,
            'notRegistered' : IDL.Null,
          }),
        ],
        [],
      ),
    'createInvestment' : IDL.Func(
        [PlanId, IDL.Float64],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'insufficientBalance' : IDL.Null,
            'notFound' : IDL.Null,
          }),
        ],
        [],
      ),
    'createWithdrawal' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [
          IDL.Variant({
            'ok' : TXId,
            'insufficientBalance' : IDL.Null,
            'notRegistered' : IDL.Null,
          }),
        ],
        [],
      ),
    'getAllPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
    'getAllRecharges' : IDL.Func([], [IDL.Vec(Recharge)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReferralTree' : IDL.Func(
        [UserId],
        [
          IDL.Record({
            'level1' : IDL.Vec(UserId),
            'level2' : IDL.Vec(UserId),
            'level3' : IDL.Vec(UserId),
          }),
        ],
        ['query'],
      ),
    'getUserInvestments' : IDL.Func([UserId], [IDL.Vec(Investment)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : User, 'notFound' : IDL.Null })],
        ['query'],
      ),
    'initiateRecharge' : IDL.Func([IDL.Float64, IDL.Text], [TXId], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };