/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Investment {
  'startTime' : Timestamp,
  'active' : boolean,
  'dailyEarnings' : number,
  'planId' : PlanId,
  'userId' : UserId,
  'totalEarned' : number,
  'amount' : number,
}
export interface InvestmentPlan {
  'id' : bigint,
  'durationDays' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'dailyReturn' : number,
  'price' : number,
}
export type PlanId = bigint;
export interface Recharge {
  'id' : TXId,
  'status' : RechargeStatus,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'paymentRef' : string,
  'amount' : number,
}
export type RechargeStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TXId = bigint;
export type Timestamp = bigint;
export interface User {
  'referralCode' : string,
  'username' : string,
  'totalRecharged' : number,
  'totalEarned' : number,
  'referredBy' : [] | [string],
  'totalWithdrawn' : number,
  'lastDailyClaim' : Timestamp,
  'phone' : string,
  'walletBalance' : number,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'id' : TXId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'paymentDetails' : string,
  'timestamp' : Timestamp,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdatePlan' : ActorMethod<[InvestmentPlan], PlanId>,
  'approveRecharge' : ActorMethod<[TXId], undefined>,
  'approveWithdrawal' : ActorMethod<[TXId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyEarnings' : ActorMethod<
    [],
    { 'ok' : number } |
      { 'dailyLimitReached' : null } |
      { 'notRegistered' : null }
  >,
  'createInvestment' : ActorMethod<
    [PlanId, number],
    { 'ok' : null } |
      { 'insufficientBalance' : null } |
      { 'notFound' : null }
  >,
  'createWithdrawal' : ActorMethod<
    [number, string],
    { 'ok' : TXId } |
      { 'insufficientBalance' : null } |
      { 'notRegistered' : null }
  >,
  'getAllPlans' : ActorMethod<[], Array<InvestmentPlan>>,
  'getAllRecharges' : ActorMethod<[], Array<Recharge>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReferralTree' : ActorMethod<
    [UserId],
    {
      'level1' : Array<UserId>,
      'level2' : Array<UserId>,
      'level3' : Array<UserId>,
    }
  >,
  'getUserInvestments' : ActorMethod<[UserId], Array<Investment>>,
  'getUserProfile' : ActorMethod<
    [UserId],
    { 'ok' : User } |
      { 'notFound' : null }
  >,
  'initiateRecharge' : ActorMethod<[number, string], TXId>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'updateUserProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];