/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface Withdrawal {
    id: TXId;
    status: WithdrawalStatus;
    userId: UserId;
    paymentDetails: string;
    timestamp: Timestamp;
    amount: number;
}
export type TXId = bigint;
export interface User {
    referralCode: string;
    username: string;
    totalRecharged: number;
    totalEarned: number;
    referredBy?: string;
    totalWithdrawn: number;
    lastDailyClaim: Timestamp;
    phone: string;
    walletBalance: number;
}
export interface InvestmentPlan {
    id: bigint;
    durationDays: bigint;
    active: boolean;
    name: string;
    description: string;
    dailyReturn: number;
    price: number;
}
export interface Investment {
    startTime: Timestamp;
    active: boolean;
    dailyEarnings: number;
    planId: PlanId;
    userId: UserId;
    totalEarned: number;
    amount: number;
}
export type PlanId = bigint;
export interface Recharge {
    id: TXId;
    status: RechargeStatus;
    userId: UserId;
    timestamp: Timestamp;
    paymentRef: string;
    amount: number;
}
export enum RechargeStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ok_insufficientBalance_notFound {
    ok = "ok",
    insufficientBalance = "insufficientBalance",
    notFound = "notFound"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdatePlan(plan: InvestmentPlan): Promise<PlanId>;
    approveRecharge(rechargeId: TXId): Promise<void>;
    approveWithdrawal(withdrawalId: TXId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimDailyEarnings(): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "dailyLimitReached";
        dailyLimitReached: null;
    } | {
        __kind__: "notRegistered";
        notRegistered: null;
    }>;
    createInvestment(planId: PlanId, amount: number): Promise<Variant_ok_insufficientBalance_notFound>;
    createWithdrawal(amount: number, paymentDetails: string): Promise<{
        __kind__: "ok";
        ok: TXId;
    } | {
        __kind__: "insufficientBalance";
        insufficientBalance: null;
    } | {
        __kind__: "notRegistered";
        notRegistered: null;
    }>;
    getAllPlans(): Promise<Array<InvestmentPlan>>;
    getAllRecharges(): Promise<Array<Recharge>>;
    getAllUsers(): Promise<Array<User>>;
    getAllWithdrawals(): Promise<Array<Withdrawal>>;
    getCallerUserProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole>;
    getReferralTree(userId: UserId): Promise<{
        level1: Array<UserId>;
        level2: Array<UserId>;
        level3: Array<UserId>;
    }>;
    getUserInvestments(userId: UserId): Promise<Array<Investment>>;
    getUserProfile(userId: UserId): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "notFound";
        notFound: null;
    }>;
    initiateRecharge(amount: number, paymentRef: string): Promise<TXId>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(username: string, phone: string, referralCode: string): Promise<void>;
    saveCallerUserProfile(profile: User): Promise<void>;
    updateUserProfile(phone: string): Promise<void>;
}
import type { Recharge as _Recharge, RechargeStatus as _RechargeStatus, TXId as _TXId, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, Withdrawal as _Withdrawal, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdatePlan(arg0: InvestmentPlan): Promise<PlanId> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePlan(arg0);
            return result;
        }
    }
    async approveRecharge(arg0: TXId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRecharge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRecharge(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: TXId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimDailyEarnings(): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "dailyLimitReached";
        dailyLimitReached: null;
    } | {
        __kind__: "notRegistered";
        notRegistered: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyEarnings();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyEarnings();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvestment(arg0: PlanId, arg1: number): Promise<Variant_ok_insufficientBalance_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvestment(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvestment(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWithdrawal(arg0: number, arg1: string): Promise<{
        __kind__: "ok";
        ok: TXId;
    } | {
        __kind__: "insufficientBalance";
        insufficientBalance: null;
    } | {
        __kind__: "notRegistered";
        notRegistered: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawal(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawal(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlans(): Promise<Array<InvestmentPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return result;
        }
    }
    async getAllRecharges(): Promise<Array<Recharge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecharges();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecharges();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralTree(arg0: UserId): Promise<{
        level1: Array<UserId>;
        level2: Array<UserId>;
        level3: Array<UserId>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralTree(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralTree(arg0);
            return result;
        }
    }
    async getUserInvestments(arg0: UserId): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInvestments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInvestments(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: User;
    } | {
        __kind__: "notFound";
        notFound: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateRecharge(arg0: number, arg1: string): Promise<TXId> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateRecharge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateRecharge(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_User_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_User_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_RechargeStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeStatus): RechargeStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Recharge_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recharge): Recharge {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_User_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Withdrawal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Withdrawal): Withdrawal {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    username: string;
    totalRecharged: number;
    totalEarned: number;
    referredBy: [] | [string];
    totalWithdrawn: number;
    lastDailyClaim: _Timestamp;
    phone: string;
    walletBalance: number;
}): {
    referralCode: string;
    username: string;
    totalRecharged: number;
    totalEarned: number;
    referredBy?: string;
    totalWithdrawn: number;
    lastDailyClaim: Timestamp;
    phone: string;
    walletBalance: number;
} {
    return {
        referralCode: value.referralCode,
        username: value.username,
        totalRecharged: value.totalRecharged,
        totalEarned: value.totalEarned,
        referredBy: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.referredBy)),
        totalWithdrawn: value.totalWithdrawn,
        lastDailyClaim: value.lastDailyClaim,
        phone: value.phone,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TXId;
    status: _WithdrawalStatus;
    userId: _UserId;
    paymentDetails: string;
    timestamp: _Timestamp;
    amount: number;
}): {
    id: TXId;
    status: WithdrawalStatus;
    userId: UserId;
    paymentDetails: string;
    timestamp: Timestamp;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n18(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        paymentDetails: value.paymentDetails,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TXId;
    status: _RechargeStatus;
    userId: _UserId;
    timestamp: _Timestamp;
    paymentRef: string;
    amount: number;
}): {
    id: TXId;
    status: RechargeStatus;
    userId: UserId;
    timestamp: Timestamp;
    paymentRef: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_RechargeStatus_n9(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        paymentRef: value.paymentRef,
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): RechargeStatus {
    return "pending" in value ? RechargeStatus.pending : "completed" in value ? RechargeStatus.completed : "failed" in value ? RechargeStatus.failed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n12(_uploadFile, _downloadFile, value.ok)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: number;
} | {
    dailyLimitReached: null;
} | {
    notRegistered: null;
}): {
    __kind__: "ok";
    ok: number;
} | {
    __kind__: "dailyLimitReached";
    dailyLimitReached: null;
} | {
    __kind__: "notRegistered";
    notRegistered: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "dailyLimitReached" in value ? {
        __kind__: "dailyLimitReached",
        dailyLimitReached: value.dailyLimitReached
    } : "notRegistered" in value ? {
        __kind__: "notRegistered",
        notRegistered: value.notRegistered
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    insufficientBalance: null;
} | {
    notFound: null;
}): Variant_ok_insufficientBalance_notFound {
    return "ok" in value ? Variant_ok_insufficientBalance_notFound.ok : "insufficientBalance" in value ? Variant_ok_insufficientBalance_notFound.insufficientBalance : "notFound" in value ? Variant_ok_insufficientBalance_notFound.notFound : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TXId;
} | {
    insufficientBalance: null;
} | {
    notRegistered: null;
}): {
    __kind__: "ok";
    ok: TXId;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "notRegistered";
    notRegistered: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "insufficientBalance" in value ? {
        __kind__: "insufficientBalance",
        insufficientBalance: value.insufficientBalance
    } : "notRegistered" in value ? {
        __kind__: "notRegistered",
        notRegistered: value.notRegistered
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Withdrawal>): Array<Withdrawal> {
    return value.map((x)=>from_candid_Withdrawal_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recharge>): Array<Recharge> {
    return value.map((x)=>from_candid_Recharge_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_User_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): _User {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    username: string;
    totalRecharged: number;
    totalEarned: number;
    referredBy?: string;
    totalWithdrawn: number;
    lastDailyClaim: Timestamp;
    phone: string;
    walletBalance: number;
}): {
    referralCode: string;
    username: string;
    totalRecharged: number;
    totalEarned: number;
    referredBy: [] | [string];
    totalWithdrawn: number;
    lastDailyClaim: _Timestamp;
    phone: string;
    walletBalance: number;
} {
    return {
        referralCode: value.referralCode,
        username: value.username,
        totalRecharged: value.totalRecharged,
        totalEarned: value.totalEarned,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        totalWithdrawn: value.totalWithdrawn,
        lastDailyClaim: value.lastDailyClaim,
        phone: value.phone,
        walletBalance: value.walletBalance
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
